name: Generate Snake

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Create assets/snake directory if it doesn't exist
        run: |
          if [ ! -d "assets/snake" ]; then
            mkdir -p assets/snake
          fi
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake/github-contribution-grid-snake.svg?color_snake=#2a7aef
            assets/snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#2a7aef
            # assets/snake/ocean.gif?color_snake=#2a7aef
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/snake
          git commit -m "updated snake"
          git push

  build_on_push:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'update snake')
    steps:
      - uses: actions/checkout@v2
      - name: Create assets/snake directory if it doesn't exist
        run: |
          if [ ! -d "assets/snake" ]; then
            mkdir -p assets/snake
          fi
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake/github-contribution-grid-snake.svg?color_snake=#2a7aef
            assets/snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#2a7aef
            # assets/snake/ocean.gif?color_snake=#2a7aef
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/snake
          git commit -m "updated snake"
          git push